version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  configuration: docs/conf.py
  builder: html
  fail_on_warning: false

formats:
  - htmlzip
  - pdf
  - epub

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev
    - requirements: docs/requirements.txt

search:
  ranking:
    api/*: -1
    guides/*: 4 